[package]
name = "iCaly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icalendar = "0.16.0"
serenity = "0.12.1"
tokio = { version = "1.37.0", features = ["full"] }
